# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/universal2100-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter o1s t2s p3s,$(TARGET_DEVICE)),)

endif
